<a href="https://colab.research.google.com/github/victorlee079/victorlee079.github.io/blob/main/convolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from scipy import signal

In [ ]:
I = np.array([[2, 2, 2, 2], [2, 2, 2, 2], [2, 1, 2, 2], [2, 2, 2, 2]])
HX = np.array([[-1, 0, 1], [-1, 0, 1], [-1, 0, 1]])
HY = np.array([[1, 1, 1], [0, 0, 0], [-1, -1, -1]])
print(I)
print(HX)
print(HY)

[[2 2 2 2]
 [2 2 2 2]
 [2 1 2 2]
 [2 2 2 2]]
[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]
[[ 1  1  1]
 [ 0  0  0]
 [-1 -1 -1]]


In [ ]:
EX = signal.convolve2d(I, HX, 'valid')
EY = signal.convolve2d(I, HY, 'valid')
print(EX)
print(EY)
GX = np.sqrt(EX*EX+EY*EY)
print(GX)

[[ 0 -1]
 [ 0 -1]]
[[-1 -1]
 [ 0  0]]
[[1.         1.41421356]
 [0.         1.        ]]


In [ ]:
I = np.array([[1, 0, 0, 0], [1, 1, 0 ,1], [0, 0, 1, 0], [1, 0, 1, 0]])
H = np.array([[-1, 0], [0, 1]])

print(signal.convolve2d(I, H))

[[-1  0  0  0  0]
 [-1  0  0 -1  0]
 [ 0  1  0  0  1]
 [-1  0 -1  1  0]
 [ 0  1  0  1  0]]
